version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ftp_data:/home/ftpusers
      - vsftpd_config:/etc/vsftpd
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

volumes:
  ftp_data:
  vsftpd_config:

networks:
  app-network:
    driver: bridge 