version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ftp_data:/home/ftpusers
      - vsftpd_config:/etc/vsftpd
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    networks:
      - app-network
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # PostgreSQL para produção
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ftp_dashboard
      POSTGRES_USER: ftp_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  ftp_data:
  vsftpd_config:
  postgres_data:

networks:
  app-network:
    driver: bridge 